fonts/opentype/public/tex-gyre/*.otf usr/share/texmf/fonts/opentype/public/tex-gyre
fonts/opentype/public/tex-gyre-math/*.otf usr/share/texmf/fonts/opentype/public/tex-gyre-math
doc/fonts/tex-gyre/* usr/share/texmf/doc/fonts/tex-gyre
doc/fonts/tex-gyre-math/* usr/share/texmf/doc/fonts/tex-gyre-math
source/fonts/tex-gyre-math/* usr/share/texmf/source/fonts/tex-gyre-math
debian/65-fonts-texgyre.conf etc/fonts/conf.avail
